version: 2
jobs:
  test_6:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: yarn install --no-progress
      - run: yarn run lint
      - run: yarn run build
      - run: yarn run test
  test_8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn install --no-progress
      - run: yarn run lint
      - run: yarn run build
      - run: yarn run test
  test_9:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: yarn install --no-progress
      - run: yarn run lint
      - run: yarn run build
      - run: yarn run test
      - run: yarn run coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - test_6
      - test_8
      - test_9